// =============================================================
// vault-data.js — data layer for vault.html (The Vault).
//
// A NEW, SEPARATE namespace: every key is 'vault:*' and syncs under its
// own Supabase appKey 'vault'. It does not read or write 'enthub:*',
// 'entdash:*', 'entread:*', 'media:*' or any other page's keys, so the
// existing Entertainment dashboard is completely unaffected by anything
// that happens here.
//
// SEED DATA. The podcasts below were transferred out of
// entertainment-dash.html#podcasts. They were archived byte-for-byte,
// reconciled against the older entertainment.html library, de-duplicated
// by canonical URL and conservation-checked before landing here — see
// WEBSITE BUILDING/data/import-report.md for the full accounting.
// Nothing was deleted from the source; this is a copy.
//
// Generated by tools/emit-vault-data.mjs — regenerate rather than
// hand-editing the SEED block.
// =============================================================
(function (global) {
  'use strict';

  // Same defensive wrapper every other -data.js here uses: a failed write
  // (most likely a full quota) must be visible, not silent.
  function storeGet(key) {
    try { const raw = localStorage.getItem(key); return raw == null ? null : JSON.parse(raw); }
    catch (e) { return null; }
  }
  function storeSet(key, value) {
    try {
      localStorage.setItem(key, JSON.stringify(value));
      try { global.dispatchEvent(new CustomEvent('vault:save', { detail: { key: key, ok: true } })); } catch (e2) {}
      return true;
    } catch (e) {
      try { global.dispatchEvent(new CustomEvent('vault:save', { detail: { key: key, ok: false, error: e } })); } catch (e2) {}
      return false;
    }
  }

  var SHELVES = ["podcasts","creepypasta","trueHorror","spicy","immersive","watch","playlists"];
  var keyFor = function (shelf) { return 'vault:media:' + shelf; };

  var SEED = {
  podcasts: [
    {
      "id": "ei_ms11e8mm_fkqdgq",
      "title": "DEBRIEFED - An AREA52 Podcast with Chris Ramsay",
      "url": "https://www.youtube.com/playlist?list=PLI6QOLLB2jIfwijne4pyLLr7Ug0M6RQbS",
      "cover": "https://i.ytimg.com/vi/Cv-sk4vt-qU/hqdefault.jpg",
      "creator": "Area52",
      "description": "Join Chris Ramsay as he debriefs the latest episode of Area52.  Through personal stories and insights, we explore the unknown and uncover hidden truths.",
      "category": "Learning",
      "lengthText": "",
      "notes": "",
      "rating": 5,
      "favorite": false,
      "queued": false,
      "order": 0,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1783658157081,
      "updatedAt": 1785024325678,
      "source": "youtube",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_ms11e8mm_fkqdgq"
    },
    {
      "id": "ei_ms17bu2s_wmtalh",
      "title": "The Blurry Creatures Podcast",
      "url": "https://www.youtube.com/playlist?list=PLT_O8HdTjHingSviNWWTRUZmrp72bd6u3",
      "cover": "https://i.ytimg.com/vi/z-Gusmpxxqg/hqdefault.jpg",
      "creator": "Blurry Creatures Podcast",
      "description": "",
      "category": "Learning",
      "lengthText": "",
      "notes": "",
      "rating": 4,
      "favorite": false,
      "queued": false,
      "order": 1,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1783658174910,
      "updatedAt": 1785034291204,
      "source": "youtube",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_ms17bu2s_wmtalh"
    },
    {
      "id": "ei_ms11hspe_oja0xl",
      "title": "Ninjas are Butterflies Podcast",
      "url": "https://www.youtube.com/playlist?list=PLnrQGD2lbP5nrWwhSi9SjNTTstqHIaMPR",
      "cover": "https://i.ytimg.com/vi/GDvo78Ur_Ds/hqdefault.jpg",
      "creator": "Ninjas Are Butterflies",
      "description": "Ninjas Are Butterflies (powered by Sunday Cool) is an outrageous comedy podcast with hosts Josh Hooper and Andy DeNoon. Filled with hilarious guests, captivating stories, and loads of laughter, Ninjas Are Butterflies is sure to be your new favorite podcast! \nNew episodes drop every Friday!",
      "category": "Learning",
      "lengthText": "",
      "notes": "",
      "rating": 5,
      "favorite": true,
      "queued": false,
      "order": 2,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1783658188082,
      "updatedAt": 1785038604331,
      "source": "youtube",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_ms11hspe_oja0xl"
    },
    {
      "id": "ei_ms11cxjj_7stacj",
      "title": "ATT  Podcast Archives",
      "url": "https://www.youtube.com/playlist?list=PLSW1ury9MFf2p6YLsMCgw0QEjEqlwJcQR",
      "cover": "https://i.ytimg.com/vi/cS5wre7tI7Q/hqdefault.jpg",
      "creator": "Alien Theorists Theorizing",
      "description": "10+ years. 450+ episodes. Every conspiracy, cryptid, and cover-up \nwe've ever investigated — all in one place.\n\nThis is the complete Alien Theorists Theorizing audio archive. From \nour earliest case files to the episodes that built the ATT community, \nit's all here for the true believers who want to go down the rabbit hole.\n\nNew to the show? Start here and catch up on the cases that started it all. Or find the show on any podcast player.",
      "category": "Learning",
      "lengthText": "",
      "notes": "",
      "rating": 5,
      "favorite": true,
      "queued": false,
      "order": 3,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1783658262646,
      "updatedAt": 1785038598829,
      "source": "youtube",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_ms11cxjj_7stacj"
    },
    {
      "id": "ei_ms17b4af_vpg4fo",
      "title": "The Why Files: Operation Podcast",
      "url": "https://www.youtube.com/playlist?list=PLaEJLf99gDO5ESB0giCaJnXQtWnx1MDaY",
      "cover": "https://i.ytimg.com/vi/hf8MORyNcgM/hqdefault.jpg",
      "creator": "The Why Files",
      "description": "Dive deep into the unknown with The Why Files: Operation Podcast! We explore mind-bending mysteries, strange phenomena, and the questions science can't (or won't) answer. Get ready to binge-listen to every episode and uncover the truth... or something like it.",
      "category": "Learning",
      "lengthText": "",
      "notes": "",
      "rating": 5,
      "favorite": true,
      "queued": false,
      "order": 4,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1783658281334,
      "updatedAt": 1785038605709,
      "source": "youtube",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_ms17b4af_vpg4fo"
    },
    {
      "id": "ei_ms11dppm_0zh91i",
      "title": "Dawn of the New Earth (The Neogenian Dawn)",
      "url": "https://www.youtube.com/playlist?list=PLFJvMzH1hHK_1z5sFctbAwLKjkH4D6vDa",
      "cover": "https://i.ytimg.com/vi/wXk_8o5eLYI/hqdefault.jpg",
      "creator": "MorgueOfficial",
      "description": "We are here to create the new earth through a new consciousness. We explore topics such as quantum mechanics, the occult, the Neogenian system, and more for the purpose of raising awareness. Hosted by morgueofficial",
      "category": "Learning",
      "lengthText": "",
      "notes": "",
      "rating": 5,
      "favorite": false,
      "queued": false,
      "order": 5,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1783658301828,
      "updatedAt": 1785024301162,
      "source": "youtube",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_ms11dppm_0zh91i"
    },
    {
      "id": "ei_ms11faxb_28il7y",
      "title": "Mind Melds",
      "url": "https://www.youtube.com/playlist?list=PLAcnJ50STeem8qmSv67aHdelpGIk9jeFK",
      "cover": "https://i.ytimg.com/vi/XGyKdLBuPY8/hqdefault.jpg",
      "creator": "THIRD EYE DROPS with Michael Phillip",
      "description": "Meld minds with Michael Phillip and his brilliant multidisciplinary guests.",
      "category": "Learning",
      "lengthText": "",
      "notes": "",
      "rating": 5,
      "favorite": false,
      "queued": false,
      "order": 6,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1783658313928,
      "updatedAt": 1785024375311,
      "source": "youtube",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_ms11faxb_28il7y"
    },
    {
      "id": "ei_ms11h8wo_t56rpm",
      "title": "Next Level Soul Podcast with Alex Ferrari",
      "url": "https://www.youtube.com/playlist?list=PLbuNduy9iZu__hWPQWRyhZ2XpuCapH3nL",
      "cover": "https://i.ytimg.com/vi/pLUH3Aw_Ni4/hqdefault.jpg",
      "creator": "Next Level Soul Podcast",
      "description": "The Next Level Soul® Podcast is a podcast that helps you navigate life's journey and connect with the power within you to make changes in your life. Host Alex Ferrari asks the big questions about living and thriving in the world today by having candid and inspiring conversations with some of the world's best teachers and thought leaders from every walk of life.\n\nThe show covers all aspects of your life's journey like spiritual inquiry, personal growth, mental health, social healing, inner healing, self-care, self-love, yoga, meditation, near-death experiences (NDE), speaking to channelers, spiritual masters, yogis, and mediums, wellness, business, money, entrepreneurship, relationships, and the integration of your mind, body, and soul. We are here to help you shift your level of consciousness and help you on your life's journey.",
      "category": "Learning",
      "lengthText": "",
      "notes": "",
      "rating": 3,
      "favorite": false,
      "queued": false,
      "order": 7,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1783658326990,
      "updatedAt": 1785024466008,
      "source": "youtube",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_ms11h8wo_t56rpm"
    },
    {
      "id": "ei_ms1798vk_lw0g8k",
      "title": "The Confessionals Episodes",
      "url": "https://www.youtube.com/playlist?list=PLW-quZH9uFxxkFa_0L-Mq1Qxyvbz0eYzh",
      "cover": "https://i.ytimg.com/vi/Gv_8uclAZsw/hqdefault.jpg",
      "creator": "The Confessionals",
      "description": "A playlist of the public episodes of The Confessionals podcast.",
      "category": "Learning",
      "lengthText": "",
      "notes": "",
      "rating": 3,
      "favorite": false,
      "queued": false,
      "order": 8,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1783658340088,
      "updatedAt": 1785034170416,
      "source": "youtube",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_ms1798vk_lw0g8k"
    },
    {
      "id": "ei_ms11evtd_di36kl",
      "title": "Metaphysical with Rob Counts & John Vivanco",
      "url": "https://www.youtube.com/playlist?list=PLFMoFjYraThZydW8cjxOTJFtbvWOC9VWw",
      "cover": "https://i.ytimg.com/vi/PgLoDXTLCak/hqdefault.jpg",
      "creator": "Metaphysical",
      "description": "Metaphysical was created in 2022 to share with the public the captivating conversations that remote viewer John Vivanco and investigative researcher Rob Counts were having each week.\n\nMetaphysical is the first show to bridge the gap between the spiritual and scientific worlds using both investigative research and remote viewing data.\n\nTopics have ranged from inspiring ancient history to mysterious legends, from strange space phenomena to unbelievable cryptids. John and Rob openly search for the truth about ancient history, interdimensional beings, paranormal phenomena, and the human spirit—and have fun doing it. \nWhile their individual knowledge of artistic, esoteric, historical, and otherworldly information does overlap with each other, their unique backgrounds and interests bring an enjoyable dynamic to each show that not only fascinates listeners, but also entertains them with John’s subtle humor and Rob’s quick wit. Metaphysical is produced by Rise.TV and has received positive feedback from hundreds of thousands of viewers.",
      "category": "Learning",
      "lengthText": "",
      "notes": "",
      "rating": 5,
      "favorite": false,
      "queued": false,
      "order": 9,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1783658351577,
      "updatedAt": 1785024355729,
      "source": "youtube",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_ms11evtd_di36kl"
    },
    {
      "id": "ei_ms11bzyz_bbq5k6",
      "title": "American Alchemy",
      "url": "https://www.youtube.com/playlist?list=PLpvZy2482-kjlxGoFLPHJFQ1lNRD_49uN",
      "cover": "https://i.ytimg.com/vi/uVVqFg2v7ro/hqdefault.jpg",
      "creator": "Jesse Michels",
      "description": "Exploring the nature of reality.\nAmerican Alchemy is hosted by Jesse Michels.",
      "category": "Learning",
      "lengthText": "",
      "notes": "",
      "rating": 5,
      "favorite": false,
      "queued": false,
      "order": 10,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1783658366389,
      "updatedAt": 1785024221147,
      "source": "youtube",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_ms11bzyz_bbq5k6"
    },
    {
      "id": "ei_ms17a6qc_70b5rj",
      "title": "The InBetween OFFICIAL Podcast",
      "url": "https://www.youtube.com/playlist?list=PLabgWwQTZM0mADZWom8BTR97-t1eG7zet",
      "cover": "https://i.ytimg.com/vi/izHGi1HN8o4/hqdefault.jpg",
      "creator": "The InBetween",
      "description": "Join Carol Ann as she dives deep into the world's most bizarre stories, eerie phenomena, and mind-bending mysteries. With her signature energetic and expressive storytelling style, Carol Ann makes you feel like she's speaking directly to you—sharing tales of cryptid encounters, paranormal experiences, historical enigmas, and unexplained events that challenge everything you think you know about reality.\nFrom firsthand dogman and bigfoot encounters to ancient mysteries like giants and lost civilizations, from time slips to UFO incidents, The InBetween explores the space between the known and unknown. Occasionally joined by her husband Antony (Mr. InBetween), Carol Ann brings passion and authenticity to every story, treating each encounter with respect while asking the questions mainstream media won't touch.",
      "category": "Learning",
      "lengthText": "",
      "notes": "",
      "rating": 4,
      "favorite": false,
      "queued": false,
      "order": 11,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1783658380989,
      "updatedAt": 1785034214292,
      "source": "youtube",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_ms17a6qc_70b5rj"
    },
    {
      "id": "ei_ms11g00q_8qxo1u",
      "title": "Must Watch Videos",
      "url": "https://www.youtube.com/playlist?list=PL8PPtxxTQjQumCkpAp8QexdT_WCetMkvU",
      "cover": "https://i.ytimg.com/vi/bJEYTjSM94s/hqdefault.jpg",
      "creator": "Bright Insight",
      "description": "",
      "category": "Learning",
      "lengthText": "",
      "notes": "",
      "rating": 5,
      "favorite": false,
      "queued": false,
      "order": 12,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1783658396143,
      "updatedAt": 1785024407834,
      "source": "youtube",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_ms11g00q_8qxo1u"
    },
    {
      "id": "ei_ms11ggt4_fonu1n",
      "title": "New Episodes",
      "url": "https://www.youtube.com/playlist?list=PLcsUJ_TZVcQP1EJrpLj2-57VKQX2TmsP0",
      "cover": "https://i.ytimg.com/vi/REXl4Dtm69g/hqdefault.jpg",
      "creator": "ACID FOR SQUARES",
      "description": "What’s up, earthlings? We’re not sure if you have heard but things have been getting pretty weird down here on planet earth. The US government has finally acknowledged the existence of UFO’s, after being caught in a lengthy coverup. Breakthrough scientific studies have proven that Psychedelic drugs are a miracle medicine with the power to induce real-life mystical experiences. While quantum physicists have proven that everything is made of energy and what we perceive with our senses is merely an illusion… leading many to believe that we might be living in some sort of simulation. More and more each day, modern science is proving what eastern mystics and indigenous shamans have been trying to tell us for thousands of years… catalyzing a massive shift in global consciousness where millions of people are rejecting the status quo and questioning everything they thought they knew about reality. That is why we have created the ACID FOR SQUARES PODCAST. A weekly show that will interview scientists, shamans, doctors, mystics, whistle-blowers, and leading experts in the fields of both science and spirituality. Embarking on a journey to uncover the mysteries of the universe and unlock the power of the human potential. As we attempt to figure out what the f**ck is going on down here on planet Earth. Join hosts Cody Blue & Tanya Dahl as they venture down the cosmic rabbit hole to explain the unexplainable, explore the unconventional, and heal the unhealable. On a mission to prove once and for all that Truth Really is Stranger Than Fiction.",
      "category": "Learning",
      "lengthText": "",
      "notes": "",
      "rating": 3,
      "favorite": false,
      "queued": false,
      "order": 13,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1783658413605,
      "updatedAt": 1785024429592,
      "source": "youtube",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_ms11ggt4_fonu1n"
    },
    {
      "id": "ei_mse1nbab_qonn06",
      "title": "Photography & Videography",
      "url": "https://www.youtube.com/playlist?list=PLutGxsfy1zaPzH2F6Z5nuqT_2NlDtFQQo",
      "cover": "https://i.ytimg.com/vi/LrdyzfwZEvw/hqdefault.jpg",
      "creator": "Dunna Did It",
      "description": "",
      "category": "Photography / Videography",
      "lengthText": "",
      "notes": "",
      "rating": 0,
      "favorite": false,
      "queued": false,
      "order": 14,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1785810809315,
      "updatedAt": 1785810809315,
      "source": "",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_mse1nbab_qonn06"
    },
    {
      "id": "ei_mse1oao4_mjnh6d",
      "title": "Learn Photography",
      "url": "https://www.youtube.com/playlist?list=PLoT4r1M_5v7TYbnKDN5luW65WCaubQY4M",
      "cover": "https://i.ytimg.com/vi/2OXqO_VeR5I/hqdefault.jpg",
      "creator": "Anthony Gugliotta",
      "description": "",
      "category": "Photography / Videography",
      "lengthText": "",
      "notes": "",
      "rating": 0,
      "favorite": false,
      "queued": false,
      "order": 15,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1785810855172,
      "updatedAt": 1785810855172,
      "source": "",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_mse1oao4_mjnh6d"
    },
    {
      "id": "ei_mse1ouj7_zmr0ks",
      "title": "Macro photography tutorials",
      "url": "https://www.youtube.com/playlist?list=PLu_4Ueevkw3z0j3esCozhiPC-m42qjc7i",
      "cover": "https://i.ytimg.com/vi/OK5PaTTes4Y/hqdefault.jpg",
      "creator": "Andrew Lanxon Photography",
      "description": "",
      "category": "Photography / Videography",
      "lengthText": "",
      "notes": "",
      "rating": 0,
      "favorite": false,
      "queued": false,
      "order": 16,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1785810880915,
      "updatedAt": 1785810880915,
      "source": "",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_mse1ouj7_zmr0ks"
    },
    {
      "id": "ei_mse1pkkr_kth0n0",
      "title": "Photography Tips and Tutorials",
      "url": "https://www.youtube.com/playlist?list=PLrAo_sXKs7cdzEj-L6MGc9Espyy7VYuqT",
      "cover": "https://i.ytimg.com/vi/Lf-jyg_s5-4/hqdefault.jpg",
      "creator": "Michael Shainblum",
      "description": "",
      "category": "Photography / Videography",
      "lengthText": "",
      "notes": "",
      "rating": 0,
      "favorite": false,
      "queued": false,
      "order": 17,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1785810914667,
      "updatedAt": 1785810914667,
      "source": "",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_mse1pkkr_kth0n0"
    },
    {
      "id": "ei_mse1qjny_hubj2k",
      "title": "Astrophotography from the Backyard & Beyond",
      "url": "https://www.youtube.com/playlist?list=PLt97PtQt5dJFUd8326FV3l42VcRs5yguU",
      "cover": "https://i.ytimg.com/vi/SWvl5E7LoPo/hqdefault.jpg",
      "creator": "AstroBackyard",
      "description": "",
      "category": "Photography / Videography",
      "lengthText": "",
      "notes": "",
      "rating": 0,
      "favorite": false,
      "queued": false,
      "order": 18,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1785810960142,
      "updatedAt": 1785810960142,
      "source": "",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_mse1qjny_hubj2k"
    },
    {
      "id": "ei_mse1sfji_94ahgl",
      "title": "Everything \"Color\" in Photoshop",
      "url": "https://www.youtube.com/playlist?list=PLLlSBGLVsEPJRN_LS9Lc3qgOm49s9iwZA",
      "cover": "https://i.ytimg.com/vi/EIVhk1RvbSE/hqdefault.jpg",
      "creator": "PiXimperfect",
      "description": "",
      "category": "Photography / Videography",
      "lengthText": "",
      "notes": "",
      "rating": 0,
      "favorite": false,
      "queued": false,
      "order": 19,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1785811048110,
      "updatedAt": 1785811048110,
      "source": "",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_mse1sfji_94ahgl"
    },
    {
      "id": "ei_mse1sxsd_vixjbr",
      "title": "Photoshop Tips & Tricks",
      "url": "https://www.youtube.com/playlist?list=PLLlSBGLVsEPKMMjf6kneVdIBZddBJQ2Q-",
      "cover": "https://i.ytimg.com/vi/DgbmrGwkYJs/hqdefault.jpg",
      "creator": "PiXimperfect",
      "description": "",
      "category": "Photography / Videography",
      "lengthText": "",
      "notes": "",
      "rating": 0,
      "favorite": false,
      "queued": false,
      "order": 20,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1785811071757,
      "updatedAt": 1785811071757,
      "source": "",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_mse1sxsd_vixjbr"
    },
    {
      "id": "ei_mse1tzok_og3385",
      "title": "In-Depth Concepts of Photoshop",
      "url": "https://www.youtube.com/playlist?list=PLLlSBGLVsEPLBPOHsWXM2jbPgZ-sfL0iF",
      "cover": "https://i.ytimg.com/vi/kcwHEw8x3Ig/hqdefault.jpg",
      "creator": "PiXimperfect",
      "description": "",
      "category": "Photography / Videography",
      "lengthText": "",
      "notes": "",
      "rating": 0,
      "favorite": false,
      "queued": false,
      "order": 21,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1785811120868,
      "updatedAt": 1785811120868,
      "source": "",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_mse1tzok_og3385"
    },
    {
      "id": "ei_mse1vli9_4nb00o",
      "title": "Photoshop & Lightroom Tutorials for Landscape Photography",
      "url": "https://www.youtube.com/playlist?list=PLvWu4TIkYj1Kuwn9F1ieS2RSjVov61Pl8",
      "cover": "https://i.ytimg.com/vi/LHwOIMbCBCI/hqdefault.jpg",
      "creator": "Christian Möhrle - The Phlog Photography",
      "description": "",
      "category": "Photography / Videography",
      "lengthText": "",
      "notes": "",
      "rating": 0,
      "favorite": false,
      "queued": false,
      "order": 22,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1785811195809,
      "updatedAt": 1785811195809,
      "source": "",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_mse1vli9_4nb00o"
    },
    {
      "id": "ei_mse1wptg_lftpvx",
      "title": "Photo News Fix",
      "url": "https://www.youtube.com/playlist?list=PLWbUbVp5Rk9TJO3O8uMUxGO9FaUO2pqYy",
      "cover": "https://i.ytimg.com/vi/HjjPSXzkNMg/hqdefault.jpg",
      "creator": "Jared Polin",
      "description": "",
      "category": "Photography / Videography",
      "lengthText": "",
      "notes": "",
      "rating": 0,
      "favorite": false,
      "queued": false,
      "order": 23,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1785811248052,
      "updatedAt": 1785811248052,
      "source": "",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_mse1wptg_lftpvx"
    },
    {
      "id": "ei_mse1x85d_ul0opi",
      "title": "Tutorials",
      "url": "https://www.youtube.com/playlist?list=PLWPee627x2SbJlWA3QBG5IGH5f0as0sTQ",
      "cover": "https://i.ytimg.com/vi/fa9P_O9jvdE/hqdefault.jpg",
      "creator": "Aidin Robbins",
      "description": "",
      "category": "Photography / Videography",
      "lengthText": "",
      "notes": "",
      "rating": 0,
      "favorite": false,
      "queued": false,
      "order": 24,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1785811271809,
      "updatedAt": 1785811271809,
      "source": "",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_mse1x85d_ul0opi"
    },
    {
      "id": "ei_mse1zk3h_w4qz34",
      "title": "Murder, Mystery & Makeup",
      "url": "https://www.youtube.com/playlist?list=PLCprSpAj-wvAf6l9ulK_2B_4BrHJM4j1s",
      "cover": "https://i.ytimg.com/vi/0IoJBV29zMg/hqdefault.jpg",
      "creator": "Bailey Sarian",
      "description": "",
      "category": "True Crime",
      "lengthText": "",
      "notes": "",
      "rating": 0,
      "favorite": false,
      "queued": false,
      "order": 25,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1785811380605,
      "updatedAt": 1785811380605,
      "source": "",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_mse1zk3h_w4qz34"
    },
    {
      "id": "ei_mse20389_p5k7ys",
      "title": "True Crime",
      "url": "https://www.youtube.com/playlist?list=PL9ycPFG-1P76l0Ch8J24EraCEY1LZjPpL",
      "cover": "https://i.ytimg.com/vi/u2AQMUeK9rw/hqdefault.jpg",
      "creator": "OUTLORE with Eleanor Neale",
      "description": "",
      "category": "True Crime",
      "lengthText": "",
      "notes": "",
      "rating": 0,
      "favorite": false,
      "queued": false,
      "order": 26,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1785811405401,
      "updatedAt": 1785811405401,
      "source": "",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_mse20389_p5k7ys"
    },
    {
      "id": "ei_mse20car_jz5cx1",
      "title": "WGMI Podcast",
      "url": "https://www.youtube.com/playlist?list=PLMIm7-bP_hbNJVC0jTwLIlctejYReL31S",
      "cover": "https://i.ytimg.com/vi/t0U3UREdjmo/hqdefault.jpg",
      "creator": "Brett Malinowski",
      "description": "",
      "category": "Business",
      "lengthText": "",
      "notes": "",
      "rating": 0,
      "favorite": false,
      "queued": false,
      "order": 27,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1785811417155,
      "updatedAt": 1785811417155,
      "source": "",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_mse20car_jz5cx1"
    },
    {
      "id": "ei_mse220tv_hhz312",
      "title": "Book Deep Dives",
      "url": "https://www.youtube.com/playlist?list=PLm_06ylwvMQ1fGy3vhiE_cKTAutukzTxx",
      "cover": "https://i.ytimg.com/vi/YRpMvYgWoqE/hqdefault.jpg",
      "creator": "Mik Writes",
      "description": "",
      "category": "Writing",
      "lengthText": "",
      "notes": "",
      "rating": 0,
      "favorite": false,
      "queued": false,
      "order": 28,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1785811495603,
      "updatedAt": 1785811495603,
      "source": "",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_mse220tv_hhz312"
    },
    {
      "id": "ei_mse22y5g_48sagq",
      "title": "Wizards, Warriors, & Words: A Fantasy Writing Advice Podcast",
      "url": "https://www.youtube.com/playlist?list=PLPc4elZ0UhQNNQcOjlneRyZVDBQMHjxbi",
      "cover": "https://i.ytimg.com/vi/QrJFQe0JXug/hqdefault.jpg",
      "creator": "Jed Herne",
      "description": "",
      "category": "Writing",
      "lengthText": "",
      "notes": "",
      "rating": 0,
      "favorite": false,
      "queued": false,
      "order": 29,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1785811538788,
      "updatedAt": 1785811538788,
      "source": "",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_mse22y5g_48sagq"
    },
    {
      "id": "ei_mse24vmi_hoe8vy",
      "title": "popular videos",
      "url": "https://www.youtube.com/playlist?list=PLoEy3Vq98f4t7h9_Qs7Vks9VXYKSsCfld",
      "cover": "https://i.ytimg.com/vi/OmKAfgwgCYI/hqdefault.jpg",
      "creator": "ana neu",
      "description": "",
      "category": "Writing",
      "lengthText": "",
      "notes": "",
      "rating": 0,
      "favorite": false,
      "queued": false,
      "order": 30,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1785811628826,
      "updatedAt": 1785811628826,
      "source": "",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_mse24vmi_hoe8vy"
    },
    {
      "id": "ei_mse25jzu_osi98s",
      "title": "Writing Tips",
      "url": "https://www.youtube.com/playlist?list=PL8-jsG6NG3oJsJ6LTZRtYtCHWi-5pjhQJ",
      "cover": "https://i.ytimg.com/vi/DvLu-dRkQ20/hqdefault.jpg",
      "creator": "ShaelinWrites",
      "description": "",
      "category": "Writing",
      "lengthText": "",
      "notes": "",
      "rating": 0,
      "favorite": false,
      "queued": false,
      "order": 31,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1785811660410,
      "updatedAt": 1785811660410,
      "source": "",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_mse25jzu_osi98s"
    },
    {
      "id": "ei_mse263bd_g2pbfe",
      "title": "craft",
      "url": "https://www.youtube.com/playlist?list=PLZ0458nY6eZ_txIQUap-1UtAXuEryrO_M",
      "cover": "https://i.ytimg.com/vi/OTCPkFMEdQ8/hqdefault.jpg",
      "creator": "kris | KM Fajardo",
      "description": "",
      "category": "Writing",
      "lengthText": "",
      "notes": "",
      "rating": 0,
      "favorite": false,
      "queued": false,
      "order": 32,
      "openCount": 0,
      "lastOpenedAt": null,
      "createdAt": 1785811685449,
      "updatedAt": 1785811685449,
      "source": "",
      "importedFrom": "enthub:podcasts",
      "legacyId": "ei_mse263bd_g2pbfe"
    }
  ]
  };

  function list(shelf) { return storeGet(keyFor(shelf)) || []; }
  function replaceAll(shelf, arr) { return storeSet(keyFor(shelf), arr || []); }

  function add(shelf, fields) {
    var all = list(shelf);
    var item = Object.assign({
      id: 'v_' + Date.now().toString(36) + '_' + Math.random().toString(36).slice(2, 8),
      title: '', url: '', cover: '', creator: '', description: '', category: '',
      lengthText: '', notes: '', rating: 0, favorite: false, queued: false,
      openCount: 0, lastOpenedAt: null, source: '', importedFrom: '', legacyId: '',
      createdAt: Date.now(), updatedAt: Date.now(),
    }, fields || {});
    item.order = all.length;
    all.push(item);
    replaceAll(shelf, all);
    return item;
  }

  function update(shelf, id, patch) {
    var all = list(shelf);
    var i = all.findIndex(function (x) { return x.id === id; });
    if (i < 0) return null;
    all[i] = Object.assign({}, all[i], patch, { updatedAt: Date.now() });
    replaceAll(shelf, all);
    return all[i];
  }

  /** Stamped on every card open — powers Continue and the activity stats. */
  function touch(shelf, id) {
    var it = list(shelf).find(function (x) { return x.id === id; });
    if (!it) return;
    update(shelf, id, { lastOpenedAt: Date.now(), openCount: (it.openCount || 0) + 1 });
  }

  function counts() {
    var out = {};
    SHELVES.forEach(function (s) { out[s] = list(s).length; });
    return out;
  }

  // ============================================================
  // SEEDING — additive only, and it never deletes.
  //
  // A shelf is seeded only when it is EMPTY. Anything already there wins,
  // so a re-run can't clobber edits, and an item deleted deliberately in
  // the Vault does not come back on the next load.
  //
  // Merge is by canonical URL rather than id, matching the migration: the
  // same link stored with a different tracking parameter is one item.
  // ============================================================
  function canonUrl(raw) {
    if (!raw) return '';
    try {
      var u = new URL(String(raw).trim());
      var host = u.hostname.replace(/^www\./, '').toLowerCase();
      var keep = new URLSearchParams();
      if (/youtube\.com|youtu\.be/.test(host)) {
        ['v', 'list'].forEach(function (p) { if (u.searchParams.has(p)) keep.set(p, u.searchParams.get(p)); });
      }
      var qs = keep.toString();
      return host + u.pathname.replace(/\/+$/, '') + (qs ? '?' + qs : '');
    } catch (e) { return String(raw).trim().toLowerCase(); }
  }

  function seedShelf(shelf) {
    var incoming = SEED[shelf] || [];
    if (!incoming.length) return 0;
    var existing = list(shelf);
    var have = {};
    existing.forEach(function (x) { var c = canonUrl(x.url); if (c) have[c] = true; });
    var added = incoming.filter(function (x) { var c = canonUrl(x.url); return !c || !have[c]; });
    if (!added.length) return 0;
    replaceAll(shelf, existing.concat(added.map(function (x, i) {
      return Object.assign({}, x, { order: existing.length + i });
    })));
    return added.length;
  }

  function seedNow() {
    var total = 0;
    Object.keys(SEED).forEach(function (s) { total += seedShelf(s); });
    if (total) storeSet('vault:seededAt', Date.now());
    return total;
  }

  /**
   * Race safety, same shape as every other page here. On a fresh device the
   * initial Supabase pull is still in flight at load time; seeding straight
   * away would write the seed locally and push it, duplicating whatever the
   * remote row already held. So: seed immediately only if a remote apply has
   * already happened, otherwise wait one beat for the pull, then seed only
   * what is still missing.
   */
  function maybeSeedAfterSyncAttempt(ref, onDone) {
    var run = function () {
      var n = seedNow();
      if (n && typeof onDone === 'function') onDone(n);
    };
    if (ref && ref.applied) { run(); return; }
    setTimeout(run, 1200);
  }

  global.Vault = {
    SHELVES: SHELVES,
    SEED: SEED,
    keyFor: keyFor,
    list: list,
    add: add,
    update: update,
    replaceAll: replaceAll,
    touch: touch,
    counts: counts,
    canonUrl: canonUrl,
    seedNow: seedNow,
    maybeSeedAfterSyncAttempt: maybeSeedAfterSyncAttempt,
  };
})(window);
